### ISSUE TITLE
Inference Server on NVIDIA Jetson with JP5.1.1 and TensorRT support

### ISSUE THREAD

**Issue by lakshanthad** [roboflow/inference#17]
Hello,

I have a Jetson Orin NX 16GB running JetPack 5.1.1 and want to run Roboflow open-source inference server on the device.

I am able to successfully do this using the docker command which utilizes TensorRT:

```sh
docker run --privileged --net=host --runtime=nvidia roboflow/roboflow-inference-server-trt-jetson-5.1.1:latest
```

But, how can I also utilize TensorRT with the open-source inference server running on the Jetson device?

Here I have installed the inference server via `pip install inference-gpu` on the Jetson.

Best Regards,
Lakshantha

**Comment by paulguerrie** [comment]
Hi @lakshanthad ,

To do this outside of our published docker, you'll want to install `inference-core` instead of `inference-gpu`. Then, you'll have to install `onnxruntime` on your own following the instructions here: https://elinux.org/Jetson_Zoo#ONNX_Runtime

Also, reference our dockerfile here to see how we do it: https://github.com/roboflow/inference/blob/main/docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1

**Comment by lakshanthad** [comment]
Thank you for the response. 

I will try it and feedback here.

**Comment by lakshanthad** [comment]
Hello,

I have noticed that when using the official Docker container of "roboflow/roboflow-inference-server-trt-jetson-5.1.1:latest" and also building "https://github.com/roboflow/inference/blob/main/docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1" from source, after running on Jetson Orin device with JP5.1.1, I encounter the following error:

```sh
ImportError: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
```

However when I add the below line into [this file](https://github.com/roboflow/inference/blob/main/docker/dockerfiles/Dockerfile.onnx.jetson.5.1.1) and build the image, the container runs with no problems:

```sh
ENV LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
```

Also the above container does not utilize TensorRT. So I have added the below 2 lines as well, and then TensorRT worked.

```sh
ENV ONNXRUNTIME_EXECUTION_PROVIDERS=TensorrtExecutionProvider
ENV REQUIRED_ONNX_PROVIDERS=TensorrtExecutionProvider
```

Please look into the issue and hopefully merge the changes to upstream.

Thank you.

Best Regards,
Lakshantha

**Comment by paulguerrie** [comment]
Hey @lakshanthad! Thanks for the post!

> ENV LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

We will definitely add this to our dockerfile! We'll also be working on more automated testing to try to catch these things a bit faster.

> Also the above container does not utilize TensorRT

We recently just switched our Jetson containers to defaulting to CUDA runtimes. As you noted, you can still configure Tensorrt via environment variables. Here are the [docs on that](https://docs.roboflow.com/deploy/enterprise-nvidia-jetson#step-2-run-docker-container). The reason we did this is because we are finding that, for most users, the small increase in performance of Tensorrt is not worth the model compile time on startup. 

Also note, with the above change, we have renamed the docker images to `roboflow/roboflow-inference-server-jetson-*` (dropping the `-trt-`)
