### ISSUE TITLE
Installing Inference does not work as it produces an error. 

### ISSUE THREAD

**Issue by harrykeeran12** [roboflow/inference#228]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar bug report.

### Bug

When using `pip install inference-cpu` it results in an error  
`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?` when getting the requirements to build wheel. 

### Environment

- OS: macOS Sonoma 14.2.1
- Conda version(for environment): 23.9.0
- Python version: 3.12.1
- Shell: zsh
- Hardware: MacOS M1. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by paulguerrie** [comment]
Hi @harrykeeran12 ! Thanks for the issue and sorry you're having trouble installing inference. I tested an install just now and it's working for me with a lower version of python. I also found [a stack overflow issue](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) that suggests the problem is specifically with python 3.12 and pip. So I think your options are:

1. downgrade python to <= 3.11
2. Follow the steps in the link above to get pip working properly in your 3.12 environment
