### ISSUE TITLE
Is support for ROCMExecutionProvider planned?

### ISSUE THREAD

**Issue by ak1932** [roboflow/inference#510]
### Search before asking

- [X] I have searched the Inference [issues](https://github.com/roboflow/inference/issues) and found no similar feature requests.

### Description

Support for ROCMExecutionProvider would be great

### Use case

This would make roboflow more accessible with users using amd gpu benefiting greatly.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by ak1932** [comment]
Onnxruntime has stable onnxruntime-rocm packages (though not on PyPi). Also is there any way I can temporily use ROCMExecutionProvider?

**Comment by yeldarby** [comment]
We don't plan to officially support this at the moment because we don't have any customers that need/use it and don't have any hardware to test with.

But you should be able to get hardware acceleration on ROCM using the onnxruntime-rocm package by installing it manually. It _should_ work just like the `onnxruntime-silicon` runtime does for MacOS acceleration.

Once installed, use the `ONNXRUNTIME_EXECUTION_PROVIDERS="[ROCMExecutionProvider, CPUExecutionProvider]"` environment variable to ensure that it gets picked up & used.

**Comment by ak1932** [comment]
Ohh ok. I'll try it out. Thanks for the help.
